language: csharp
solution: Heuristic.Linq.sln
dist: trusty
mono: none
dotnet: 2.1.3

install:
- dotnet restore src/Heuristic.Linq.sln

script:
- dotnet build src/Heuristic.Linq.sln
- dotnet test src/Heuristic.Linq.Test/Heuristic.Linq.Test.csproj -c Release